version: "3"

services:
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=davidalucas
      - MONGO_PASSWORD=secretpassword
      - SESSION_SECRET=secretForSession
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=davidalucas
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
